name: 'Flake8'
description: 'Flake8 linting'
inputs:
  path:
    description: 'Path to lint'
    required: true
    default: '.'
  max-line-length:
    description: 'Max line length'
    required: false
    default: '79'
runs:
  using: 'docker'
  image: 'docker://alpine/flake8'
  args:
    - ${{ inputs.path }}
    - "--max-line-length"
    - ${{ inputs.max-line-length }}
